export {
  LucideArrowRight,
  LucideBookmark,
  LucideCalendarDays,
  LucideCheck,
  LucideChevronLeft,
  LucideChevronsDown,
  LucideCircleUser,
  LucideClock,
  LucideCompass,
  LucideNavigation,
  LucidePlus,
  LucideRoute,
  LucideSlidersHorizontal,
  LucideTriangleAlert,
  LucideX,
} from '@lucide/angular';
